name: ramp-cancer
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - geopandas
  - folium
  - pip:
      - ramp-workflow
